---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Установка Docker
      block:
        - name: Добавляем репозиторий  Universe
          apt_repository:
            repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
            state: present

        - name: Установка дополнительных пакетов
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
#              - lsb_release
            update_cache: true
            cache_valid_time: 86400

        - name: Добавление ключа Docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Установка стабильного репозитория
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update_cache: true
            filename: docker

        - name: Установка Docker и Docker-Compose
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            update_cache: true
            cache_valid_time: 86400

        - name: Проверка что Docker установлен и перезагружен
          service:
            name: docker
            state: restarted
            enabled: true
      become: true

#    - name: Установка Docker compose
#      block:
#        - name: Проверка последней версии Docker compose
#          uri:
#            url: "https://api.github.com/repos/docker/compose/releases/latest"
#            body_format: json
#          register: page
#
#        - name: Установка Docker compose
#          get_url:
#            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
#            dest: /usr/local/bin/docker-compose
#            mode: 0755

    - name: Завершение установки
      block:
        - name: Проверяем наличие группы Docker
          group:
            name: docker
            state: present

        - name: Добавляем пользователя в группу Docker
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: true

        - name: Перезагрузка сервера
          reboot:
#            reboot_timeout: 300
      become: true
